## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file TMA03.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_28 = Integer(28); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_6 = Integer(6); _sage_const_34 = Integer(34); _sage_const_36 = Integer(36); _sage_const_9 = Integer(9); _sage_const_15 = Integer(15); _sage_const_11 = Integer(11); _sage_const_12 = Integer(12); _sage_const_18 = Integer(18); _sage_const_20 = Integer(20); _sage_const_22 = Integer(22); _sage_const_7 = Integer(7); _sage_const_39 = Integer(39); _sage_const_8 = Integer(8); _sage_const_14 = Integer(14); _sage_const_13 = Integer(13); _sage_const_82 = Integer(82); _sage_const_92 = Integer(92); _sage_const_105 = Integer(105); _sage_const_10 = Integer(10); _sage_const_120 = Integer(120); _sage_const_68 = Integer(68)## This file (TMA03.sagetex.sage) was *autogenerated* from TMA03.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('TMA03', version='2020/08/12 v3.5', version_check=True)
_st_.current_tex_line = _sage_const_28 
_st_.blockbegin()
try:
 m=[(_sage_const_1 , _sage_const_0 , _sage_const_1 , _sage_const_2 , _sage_const_3 , _sage_const_4 , _sage_const_5 ),
    (_sage_const_0 , _sage_const_1 , _sage_const_1 , _sage_const_1 , _sage_const_1 , _sage_const_1 , _sage_const_1 )];
 G = matrix(Integers(_sage_const_6 ),_sage_const_2 , m);
 v = matrix([_sage_const_1 , _sage_const_5 ]);
 cw = v*G;
except:
 _st_.goboom(_sage_const_34 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_36 
 _st_.inline(_sage_const_0 , latex(latex(v)))
except:
 _st_.goboom(_sage_const_36 )
try:
 _st_.current_tex_line = _sage_const_36 
 _st_.inline(_sage_const_1 , latex(latex(G)))
except:
 _st_.goboom(_sage_const_36 )
try:
 _st_.current_tex_line = _sage_const_36 
 _st_.inline(_sage_const_2 , latex(cw))
except:
 _st_.goboom(_sage_const_36 )
_st_.current_tex_line = _sage_const_2 
_st_.blockbegin()
try:
 x = SR.var('x');
 g = _sage_const_1  + x + x**_sage_const_2  + x**_sage_const_3  + x**_sage_const_6 ;
 h = _sage_const_1  + x + x**_sage_const_4  + x**_sage_const_5  + x**_sage_const_6  + x**_sage_const_9 ;
 f = x**_sage_const_15  - _sage_const_1 ;
 R = PolynomialRing(ZZ,_sage_const_1 ,order='neglex', names=('x',)); (x,) = R._first_ngens(1);
 l = R(g*h);
 R = PolynomialRing(GF(_sage_const_2 ),_sage_const_1 ,order='neglex', names=('x',)); (x,) = R._first_ngens(1);
 L = R(g*h);
except:
 _st_.goboom(_sage_const_11 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_12 
 _st_.inline(_sage_const_3 , latex(R(g)))
except:
 _st_.goboom(_sage_const_12 )
try:
 _st_.current_tex_line = _sage_const_12 
 _st_.inline(_sage_const_4 , latex(R(h)))
except:
 _st_.goboom(_sage_const_12 )
try:
 _st_.current_tex_line = _sage_const_18 
 _st_.inline(_sage_const_5 , latex(R(h)))
except:
 _st_.goboom(_sage_const_18 )
try:
 _st_.current_tex_line = _sage_const_20 
 _st_.inline(_sage_const_6 , latex(l))
except:
 _st_.goboom(_sage_const_20 )
try:
 _st_.current_tex_line = _sage_const_22 
 _st_.inline(_sage_const_7 , latex(L))
except:
 _st_.goboom(_sage_const_22 )
try:
 _st_.current_tex_line = _sage_const_39 
 _st_.inline(_sage_const_8 , latex(_sage_const_1 +_sage_const_15 +_sage_const_14 +_sage_const_13 +_sage_const_13 ))
except:
 _st_.goboom(_sage_const_39 )
_st_.current_tex_line = _sage_const_82 
_st_.blockbegin()
try:
 H= Matrix(GF(_sage_const_2 ),[
    [_sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_1 , _sage_const_1 , _sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_1 , _sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 ],
    [_sage_const_0 , _sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_1 , _sage_const_1 , _sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_1 , _sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 ],
    [_sage_const_0 , _sage_const_0 , _sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_1 , _sage_const_1 , _sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_1 , _sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_0 ],
    [_sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_1 , _sage_const_1 , _sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_1 , _sage_const_1 , _sage_const_0 , _sage_const_0 ],
    [_sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_1 , _sage_const_1 , _sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_1 , _sage_const_1 , _sage_const_0 ],
    [_sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_1 , _sage_const_1 , _sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_1 , _sage_const_1 ]
 ]);
 r = Matrix(GF(_sage_const_2 ),[_sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_1 , _sage_const_1 ]);
except:
 _st_.goboom(_sage_const_92 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_105 
 _st_.inline(_sage_const_9 , latex(_sage_const_15 -_sage_const_6 ))
except:
 _st_.goboom(_sage_const_105 )
try:
 _st_.current_tex_line = _sage_const_105 
 _st_.inline(_sage_const_10 , latex(_sage_const_2 **_sage_const_6 ))
except:
 _st_.goboom(_sage_const_105 )
try:
 _st_.current_tex_line = _sage_const_120 
 _st_.inline(_sage_const_11 , latex(_sage_const_2 **_sage_const_6 ))
except:
 _st_.goboom(_sage_const_120 )
try:
 _st_.current_tex_line = _sage_const_68 
 _st_.inline(_sage_const_12 , latex(_sage_const_1 *(_sage_const_2 *_sage_const_7 +_sage_const_1 )))
except:
 _st_.goboom(_sage_const_68 )
_st_.endofdoc()

