

# This file was *autogenerated* from the file q4a.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_6 = Integer(6); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_9 = Integer(9); _sage_const_15 = Integer(15); _sage_const_0 = Integer(0)
x = var('x');
g = _sage_const_1  + x + x**_sage_const_2  + x**_sage_const_3  + x**_sage_const_6 ;
h = _sage_const_1  + x + x**_sage_const_4  + x**_sage_const_5  + x**_sage_const_6  + x**_sage_const_9 ;
f = x**(_sage_const_15 ) - _sage_const_1 ;
#R.<x>=PolynomialRing(GF(2),1,order='neglex');
for i in range(_sage_const_0 ,_sage_const_15 ):
	l =  expand(x**i*(_sage_const_1 +x)*h);
	print(l);

